import { NextResponse } from 'next/server';
import { getUser } from '@/lib/db/queries';
import { getGenerationJobsForUser } from '@/lib/db/queries/generation';
import { getAdArchetypeByCode } from '@/lib/db/queries/ads';

// Get last 10 generation jobs for authenticated user
export async function GET(req: Request) {
  try {
    const user = await getUser();
    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { searchParams } = new URL(req.url);
    const filterAutoGenerated = searchParams.get('filterAutoGenerated') === 'true';

    const jobsResult = await getGenerationJobsForUser(user.id, 10, {
      filterAutoGenerated
    });
    
    // Transform jobs to include display names
    const jobsWithDisplayNames = await Promise.all(
      jobsResult.map(async ({ job, adImageCount }) => {
        let displayName = 'Generation job';
        const params = job.params as { source?: string } | null;
        const isCloned = !!(params && typeof params === 'object' && params.source === 'clone_ad');

        if (job.autoGenerated) {
          displayName = 'Quick ads';
        } else if (isCloned) {
          if (job.archetypeCode) {
            const archetype = await getAdArchetypeByCode(job.archetypeCode);
            displayName = archetype ? `Clone ad (${archetype.displayName})` : 'Clone ad';
          } else {
            displayName = 'Clone ad';
          }
        } else if (job.archetypeCode) {
          const archetype = await getAdArchetypeByCode(job.archetypeCode);
          if (archetype) {
            displayName = archetype.displayName;
          }
        }

        // Check if job is "new" (SUCCEEDED with completedAt but not viewed)
        const isNew =
          job.status === 'SUCCEEDED' &&
          (job.viewedAt === null || (job.viewedAt && job.completedAt && new Date(job.viewedAt) < new Date(job.completedAt))) &&
          // Exclude jobs with website_url in params (new user generation jobs)
          !(job.params && typeof job.params === 'object' && 'website_url' in job.params);

        return {
          id: job.id,
          status: job.status,
          displayName,
          createdAt: job.createdAt,
          completedAt: job.completedAt,
          viewedAt: job.viewedAt,
          archetypeCode: job.archetypeCode,
          autoGenerated: job.autoGenerated,
          isCloned,
          isNew,
          adImageCount,
        };
      })
    );

    return NextResponse.json(jobsWithDisplayNames);
  } catch (error) {
    console.error('Error fetching generation jobs:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
