"use client";

import {
  LegalPageLayout,
  LegalSection,
} from "@/app/(legal)/components/legal-page-layout";

const LAST_UPDATED = "02/19/2026";

const SECTIONS = [
  { id: "about-blumpo", label: "About Blumpo" },
  { id: "eligibility", label: "Eligibility" },
  { id: "accounts", label: "Accounts" },
  { id: "subscription-payments", label: "Subscription & Payments" },
  { id: "use-of-service", label: "Use of the Service" },
  { id: "customer-data", label: "Customer Data" },
  { id: "generated-content", label: "Generated Content" },
  { id: "intellectual-property", label: "Intellectual Property" },
  { id: "confidentiality", label: "Confidentiality" },
  { id: "disclaimer", label: "Disclaimer" },
  { id: "limitation-of-liability", label: "Limitation of Liability" },
  { id: "termination", label: "Termination" },
  { id: "changes-to-terms", label: "Changes to Terms" },
] as const;

export default function TermsPage() {
  return (
    <LegalPageLayout
      title="Terms of service"
      lastUpdated={LAST_UPDATED}
      sections={SECTIONS}
    >
      <p className="text-[#374151] text-base leading-relaxed mb-6">
        Blumpo These Terms of Service (&quot;Terms&quot;) govern access to and
        use of Blumpo&apos;s services (&quot;Service&quot;), including our
        website, applications, and related tools. By accessing or using the
        Service, you agree to be bound by these Terms.
      </p>

      <LegalSection id={SECTIONS[0].id} number={1} title="About Blumpo">
        <p>
          Blumpo provides an AI-powered platform for creating advertising and
          marketing content. Our Service helps businesses generate ad creatives
          based on their brand, audience, and goals.
        </p>
      </LegalSection>

      <LegalSection id={SECTIONS[1].id} number={2} title="Eligibility">
        <p>
          You must be at least 18 years old and have the legal capacity to enter
          into contracts to use the Service. By using the Service, you represent
          that you meet these requirements.
        </p>
      </LegalSection>

      <LegalSection id={SECTIONS[2].id} number={3} title="Accounts">
        <p>
          You may need to create an account to access certain features. You are
          responsible for maintaining the confidentiality of your account
          credentials and for all activity under your account.
        </p>
      </LegalSection>

      <LegalSection
        id={SECTIONS[3].id}
        number={4}
        title="Subscription & Payments"
      >
        <p>
          Some parts of the Service are offered on a subscription or pay-per-use
          basis. By subscribing or making a purchase, you agree to the
          applicable pricing and payment terms. Fees are generally
          non-refundable unless otherwise stated or required by law.
        </p>
      </LegalSection>

      <LegalSection id={SECTIONS[4].id} number={5} title="Use of the Service">
        <p>
          You agree to use the Service only for lawful purposes and in
          accordance with these Terms. You may not use the Service to create
          content that is illegal, harmful, infringing, or otherwise
          objectionable.
        </p>
      </LegalSection>

      <LegalSection id={SECTIONS[5].id} number={6} title="Customer Data">
        <p>
          You retain ownership of the data you provide to the Service. We
          process your data in accordance with our Privacy Policy and use it
          solely to provide and improve the Service.
        </p>
      </LegalSection>

      <LegalSection id={SECTIONS[6].id} number={7} title="Generated Content">
        <p>
          Content generated by the Service is provided for your use subject to
          these Terms and your subscription or purchase terms. We do not
          guarantee that generated content will be free of third-party rights;
          you are responsible for appropriate use and clearance.
        </p>
      </LegalSection>

      <LegalSection
        id={SECTIONS[7].id}
        number={8}
        title="Intellectual Property"
      >
        <p>
          Blumpo and its licensors own all rights in the Service, including
          software, design, and branding. These Terms do not grant you any
          rights to our intellectual property except the limited right to use
          the Service as described.
        </p>
      </LegalSection>

      <LegalSection id={SECTIONS[8].id} number={9} title="Confidentiality">
        <p>
          You may receive confidential information from us. You agree to keep
          such information confidential and not disclose it to third parties
          without our prior written consent.
        </p>
      </LegalSection>

      <LegalSection id={SECTIONS[9].id} number={10} title="Disclaimer">
        <p>
          The Service is provided &quot;as is&quot; and &quot;as available&quot;
          without warranties of any kind, either express or implied. We do not
          warrant that the Service will be uninterrupted, error-free, or free of
          harmful components.
        </p>
      </LegalSection>

      <LegalSection
        id={SECTIONS[10].id}
        number={11}
        title="Limitation of Liability"
      >
        <p>
          To the maximum extent permitted by law, Blumpo shall not be liable for
          any indirect, incidental, special, consequential, or punitive
          damages, or for any loss of profits, data, or use of the Service.
        </p>
      </LegalSection>

      <LegalSection id={SECTIONS[11].id} number={12} title="Termination">
        <p>
          We may suspend or terminate your access to the Service at any time for
          violation of these Terms or for any other reason. You may stop using
          the Service at any time.
        </p>
      </LegalSection>

      <LegalSection id={SECTIONS[12].id} number={13} title="Changes to Terms">
        <p>
          We may update these Terms from time to time. We will notify you of
          material changes by posting the updated Terms and updating the
          &quot;Last updated&quot; date. Your continued use of the Service
          after such changes constitutes acceptance of the new Terms.
        </p>
      </LegalSection>

      <p className="text-[#374151] text-base mt-8">
        If you have questions, contact{" "}
        <a
          href="mailto:support@blumpo.com"
          className="text-[#00bfa6] hover:underline"
        >
          support@blumpo.com
        </a>
        .
      </p>
    </LegalPageLayout>
  );
}
