import { NextResponse } from "next/server";
import { getUser } from "@/lib/db/queries";
import { getGenerationJobById } from "@/lib/db/queries/generation";
import { getAdImagesByJobId } from "@/lib/db/queries/ads";
import { 
  findOrCreateJobForMigration, 
  migrateFailedJobAds, 
  cleanupFailedJob 
} from "@/lib/db/queries/quick-ads";

/**
 * Manual migration endpoint for failed quick ads jobs
 * 
 * POST /api/quick-ads/migrate-failed
 * Body: { jobId?: string } // Optional: specific job ID, or migrate all failed jobs for user
 * 
 * Migrates ads from failed quick ads jobs to existing or new jobs.
 * Only migrates complete format pairs (1:1 and 9:16 with same workflowId).
 * Orphaned ads are deleted.
 */
export async function POST(req: Request) {
  try {
    
    const user = await getUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const { jobId } = body;

    // If specific jobId provided, migrate that job
    if (jobId) {
      const job = await getGenerationJobById(jobId);
      
      if (!job) {
        return NextResponse.json({ error: "Job not found" }, { status: 404 });
      }

      // Verify job belongs to user
      if (job.userId !== user.id) {
        return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
      }

      // Verify it's a quick ads job
      if (!job.autoGenerated) {
        return NextResponse.json({ 
          error: "Not a quick ads job",
          message: "This endpoint only migrates quick ads jobs (autoGenerated: true)"
        }, { status: 400 });
      }

      // Verify job is FAILED or CANCELED (not SUCCEEDED)
      if (job.status === 'SUCCEEDED' || job.status === 'RUNNING' || job.status === 'QUEUED') {
        return NextResponse.json({ 
          error: "Job is not failed",
          message: `This endpoint only migrates FAILED or CANCELED jobs. Job status: ${job.status}`
        }, { status: 400 });
      }

      // Get ads from the job
      const adImages = await getAdImagesByJobId(jobId);
      const validAds = adImages.filter(
        (img) => !img.isDeleted && !img.errorFlag && img.publicUrl
      );

      if (validAds.length === 0) {
        return NextResponse.json({
          success: true,
          message: "No valid ads to migrate",
          jobId,
          migrated: 0,
          orphaned: 0
        });
      }

      // Find or create target job
      const targetJob = await findOrCreateJobForMigration(job.userId, job.brandId);
      console.log(`[MIGRATE-FAILED] Migrating from job ${jobId} to job ${targetJob.id}`);

      // Migrate ads
      const migrationResult = await migrateFailedJobAds(jobId, targetJob.id);
      console.log(`[MIGRATE-FAILED] Migration result:`, migrationResult);

      // Clean up failed job (mark as CANCELED)
      await cleanupFailedJob(jobId);

      return NextResponse.json({
        success: true,
        message: "Migration completed",
        sourceJob: {
          id: jobId,
          status: job.status,
          adsCount: validAds.length
        },
        targetJob: {
          id: targetJob.id,
          status: targetJob.status
        },
        migration: migrationResult
      });
    }

    // If no jobId provided, find all failed quick ads jobs for this user and migrate them
    const { db } = await import('@/lib/db/drizzle');
    const { generationJob } = await import('@/lib/db/schema');
    const { eq, and, sql } = await import('drizzle-orm');

    const failedJobs = await db
      .select()
      .from(generationJob)
      .where(
        and(
          eq(generationJob.userId, user.id),
          eq(generationJob.autoGenerated, true),
          sql`${generationJob.status} IN ('FAILED', 'CANCELED')`
        )
      )
      .orderBy(generationJob.createdAt);

    if (failedJobs.length === 0) {
      return NextResponse.json({
        success: true,
        message: "No failed quick ads jobs found",
        migrated: []
      });
    }

    const migrationResults = [];

    for (const failedJob of failedJobs) {
      try {
        // Get ads from the job
        const adImages = await getAdImagesByJobId(failedJob.id);
        const validAds = adImages.filter(
          (img) => !img.isDeleted && !img.errorFlag && img.publicUrl
        );

        if (validAds.length === 0) {
          // No ads to migrate, just clean up
          await cleanupFailedJob(failedJob.id);
          migrationResults.push({
            jobId: failedJob.id,
            status: 'skipped',
            message: 'No valid ads to migrate',
            migrated: 0,
            orphaned: 0
          });
          continue;
        }

        // Find or create target job
        const targetJob = await findOrCreateJobForMigration(failedJob.userId, failedJob.brandId);

        // Migrate ads
        const migrationResult = await migrateFailedJobAds(failedJob.id, targetJob.id);

        // Clean up failed job
        await cleanupFailedJob(failedJob.id);

        migrationResults.push({
          jobId: failedJob.id,
          status: 'migrated',
          targetJobId: targetJob.id,
          ...migrationResult
        });
      } catch (error) {
        console.error(`[MIGRATE-FAILED] Error migrating job ${failedJob.id}:`, error);
        migrationResults.push({
          jobId: failedJob.id,
          status: 'error',
          error: error instanceof Error ? error.message : 'Unknown error'
        });
      }
    }

    const totalMigrated = migrationResults.reduce((sum, r) => sum + (r.migrated || 0), 0);
    const totalOrphaned = migrationResults.reduce((sum, r) => sum + (r.orphaned || 0), 0);

    return NextResponse.json({
      success: true,
      message: `Processed ${failedJobs.length} failed job(s)`,
      totalMigrated,
      totalOrphaned,
      results: migrationResults
    });
  } catch (error) {
    console.error('[MIGRATE-FAILED] Error:', error);
    return NextResponse.json(
      { 
        error: "Internal server error",
        message: error instanceof Error ? error.message : "Unknown error"
      },
      { status: 500 }
    );
  }
}

/**
 * GET endpoint to check failed jobs that can be migrated
 * 
 * GET /api/quick-ads/migrate-failed
 * Returns list of failed quick ads jobs with their ad counts
 */
export async function GET(req: Request) {
  try {
    const user = await getUser();
    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { db } = await import('@/lib/db/drizzle');
    const { generationJob, adImage } = await import('@/lib/db/schema');
    const { eq, and, sql } = await import('drizzle-orm');

    const failedJobs = await db
      .select({
        job: generationJob,
        validAdsCount: sql<number>`
          COALESCE((
            SELECT COUNT(*)::int FROM ${adImage}
            WHERE ${adImage.jobId} = ${generationJob.id}
            AND ${adImage.isDeleted} = false
            AND ${adImage.errorFlag} = false
            AND ${adImage.publicUrl} IS NOT NULL
          ), 0)
        `,
      })
      .from(generationJob)
      .where(
        and(
          eq(generationJob.userId, user.id),
          eq(generationJob.autoGenerated, true),
          sql`${generationJob.status} IN ('FAILED', 'CANCELED')`
        )
      )
      .orderBy(generationJob.createdAt);

    return NextResponse.json({
      failedJobs: failedJobs.map(row => ({
        id: row.job.id,
        status: row.job.status,
        brandId: row.job.brandId,
        createdAt: row.job.createdAt,
        completedAt: row.job.completedAt,
        errorCode: row.job.errorCode,
        errorMessage: row.job.errorMessage,
        validAdsCount: row.validAdsCount,
        canMigrate: row.validAdsCount > 0
      })),
      total: failedJobs.length,
      totalWithAds: failedJobs.filter(r => r.validAdsCount > 0).length
    });
  } catch (error) {
    console.error('[MIGRATE-FAILED] Error:', error);
    return NextResponse.json(
      { 
        error: "Internal server error",
        message: error instanceof Error ? error.message : "Unknown error"
      },
      { status: 500 }
    );
  }
}
