'use client';

import { useState, useEffect, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import Image from 'next/image';
import { X, ArrowRight, Loader2 } from 'lucide-react';
import { useBrand } from '@/lib/contexts/brand-context';

interface GenerationJob {
  id: string;
  status: 'QUEUED' | 'RUNNING' | 'SUCCEEDED' | 'FAILED' | 'CANCELED';
  displayName: string;
  createdAt: string;
  completedAt: string | null;
  viewedAt: string | null;
  isNew: boolean;
  adImageCount: number;
}

interface JobStatusCheck {
  [jobId: string]: {
    status: string;
    images: any[];
    error_message?: string;
    error_code?: string;
  } | null;
}

export function GenerationStatusPanel() {
  const [isOpen, setIsOpen] = useState(false);
  const [jobs, setJobs] = useState<GenerationJob[]>([]);
  const router = useRouter();
  const { currentBrand, setCurrentBrand } = useBrand();

  // Fetch jobs in background (doesn't block UI)
  const fetchJobs = useCallback(async () => {
    try {
      const response = await fetch('/api/generation-jobs?filterAutoGenerated=true');
      if (response.ok) {
        const data = await response.json();
        setJobs(data);
      }
    } catch (error) {
      console.error('Error fetching generation jobs:', error);
    }
  }, []);

  // Check Redis for status updates
  const checkJobStatuses = useCallback(async () => {
    // Check only running jobs
    const activeJobIds = jobs
      .filter((job) => job.status === 'RUNNING')
      .map((job) => job.id);

    if (activeJobIds.length === 0) {
      return;
    }

    try {
      const response = await fetch('/api/generation-jobs/status-check', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ jobIds: activeJobIds }),
      });

      if (response.ok) {
        const statuses: JobStatusCheck = await response.json();
        
        // Update jobs with new statuses from Redis
        const hasUpdates = Object.values(statuses).some(status => status !== null);
        if (hasUpdates) {
          setJobs((prevJobs) =>
            prevJobs.map((job) => {
              const statusUpdate = statuses[job.id];
              if (statusUpdate) {
                const newStatus = statusUpdate.status as GenerationJob['status'];
                const isCompleted = newStatus === 'SUCCEEDED' || newStatus === 'FAILED' || newStatus === 'CANCELED';
                return {
                  ...job,
                  status: newStatus,
                  isNew: newStatus === 'SUCCEEDED' && !job.viewedAt && isCompleted,
                  completedAt: isCompleted ? new Date().toISOString() : job.completedAt,
                };
              }
              return job;
            })
          );
          
          // Refresh jobs list after status update to get latest from DB
          setTimeout(() => {
            fetchJobs();
          }, 1000);
        }
      }
    } catch (error) {
      console.error('Error checking job statuses:', error);
    }
  }, [jobs]);

  // Initial fetch when component mounts (background)
  useEffect(() => {
    fetchJobs();
  }, [fetchJobs]);

  // Refresh when panel opens (background)
  useEffect(() => {
    if (isOpen) {
      fetchJobs();
    }
  }, [isOpen, fetchJobs]);

  // Poll for status updates
  useEffect(() => {
    if (!isOpen) return;

    const runningJobs = jobs.filter(
      (job) => job.status === 'RUNNING'
    );

    if (runningJobs.length === 0) {
      return;
    }

    // Poll every 2-3 seconds when panel is open
    const interval = setInterval(() => {
      checkJobStatuses();
    }, 2500);

    return () => clearInterval(interval);
  }, [isOpen, jobs, checkJobStatuses]);

  // Poll less frequently when panel is closed but icon visible
  useEffect(() => {
    if (isOpen) return;

    const runningJobs = jobs.filter(
      (job) => job.status === 'RUNNING'
    );

    if (runningJobs.length === 0) {
      return;
    }

    // Poll every 10 seconds when panel is closed
    const interval = setInterval(() => {
      checkJobStatuses();
    }, 10000);

    return () => clearInterval(interval);
  }, [isOpen, jobs, checkJobStatuses]);

  // Listen for job viewed events and refresh jobs list
  useEffect(() => {
    const handleJobViewed = () => {
      // Refetch jobs to update the badge counter
      fetchJobs();
    };

    window.addEventListener('generation-job-viewed', handleJobViewed);

    return () => {
      window.removeEventListener('generation-job-viewed', handleJobViewed);
    };
  }, [fetchJobs]);

  const handleJobClick = async (job: GenerationJob) => {
    if (job.status === 'SUCCEEDED' && job.isNew) {
      // Close panel and navigate to ad generation page (not ad-review-view)
      setIsOpen(false);
      router.push(`/dashboard/ad-generation?job_id=${job.id}`);
    }
    else if (job.status === 'SUCCEEDED' && !job.isNew) {
      // Fetch job details to get brandId
      try {
        const jobResponse = await fetch(`/api/generation-job?jobId=${job.id}`);
        if (jobResponse.ok) {
          const jobDetails = await jobResponse.json();
          
          // If job has brandId, check and update brand context if needed
          if (jobDetails.brandId) {
            // Check if current brand matches job's brand
            if (currentBrand?.id !== jobDetails.brandId) {
              // Fetch brands to find the matching brand
              const brandsResponse = await fetch('/api/brands');
              if (brandsResponse.ok) {
                const brands = await brandsResponse.json();
                const matchingBrand = brands.find((b: any) => b.id === jobDetails.brandId);
                if (matchingBrand) {
                  setCurrentBrand(matchingBrand);
                }
              }
            }
          }
        }
      } catch (error) {
        console.error('Error fetching job details:', error);
        // Continue with navigation even if brand check fails
      }
      
      // Close panel and navigate to content library with job_id
      setIsOpen(false);
      router.push(`/dashboard/content-library?job_id=${job.id}`);
    }
    else if (job.status === 'RUNNING') {
      // Close panel and navigate to ad generation page (not ad-review-view)
      setIsOpen(false);
      router.push(`/dashboard/ad-generation?job_id=${job.id}`);
    }
  };

  const getStatusColor = (status: GenerationJob['status']) => {
    switch (status) {
      case 'QUEUED':
      case 'RUNNING':
        return 'bg-gray-50';
      case 'SUCCEEDED':
        return 'bg-green-50';
      case 'FAILED':
      case 'CANCELED':
        return 'bg-red-50';
      default:
        return 'bg-gray-50';
    }
  };

  const getStatusTextColor = (status: GenerationJob['status']) => {
    switch (status) {
      case 'QUEUED':
      case 'RUNNING':
        return 'text-gray-800';
      case 'SUCCEEDED':
        return 'text-green-800';
      case 'FAILED':
      case 'CANCELED':
        return 'text-red-800';
      default:
        return 'text-gray-800';
    }
  };

  const getStatusText = (status: GenerationJob['status']) => {
    switch (status) {
      case 'QUEUED':
        return 'queued';
      case 'RUNNING':
        return 'in progress';
      case 'SUCCEEDED':
        return 'done';
      case 'FAILED':
        return 'failed';
      case 'CANCELED':
        return 'failed';
      default:
        return '';
    }
  };

  return (
    <>
      {/* Icon trigger - only visible when panel is closed */}
      <button
        onClick={() => setIsOpen(!isOpen)}
        className={`fixed right-0 top-1/2 -translate-y-1/2 z-50 p-3 bg-white rounded-l-2xl shadow-lg hover:bg-gray-50 transition-all duration-300 ease-in-out border border-r-0 border-gray-200 cursor-pointer ${
          isOpen
            ? 'opacity-0 pointer-events-none translate-x-4'
            : 'opacity-100 pointer-events-auto translate-x-0'
        }`}
        aria-label="Generation status"
      >
        <div className="relative">
          <Image
            src="/assets/icons/History.svg"
            alt="Generation history"
            width={29}
            height={29}
            className="w-[29px] h-[29px]"
          />
          {/* Badge counter for new jobs */}
          {jobs.filter(job => job.isNew).length > 0 && (
            <span className="absolute -top-2.5 -right-2.5 min-w-[20px] h-[20px] px-1 bg-green-600 text-white text-xs font-semibold rounded-full flex items-center justify-center shadow z-10">
              {jobs.filter(job => job.isNew).length}
            </span>
          )}
        </div>
      </button>

      {/* Panel */}
      <div
        className={`fixed right-0 top-1/2 -translate-y-1/2 w-80 bg-white rounded-lg shadow-2xl border border-gray-200 z-40 transform transition-transform duration-300 ease-in-out ${
          isOpen ? 'translate-x-0' : 'translate-x-full'
        }`}
        style={{ maxHeight: 'calc(100vh - 80px)' }}
      >
        <div className="flex flex-col">
          {/* Header */}
          <div className="flex items-center justify-between px-4 py-3 border-b border-gray-200">
            <span
              style={{
                fontWeight: 500,
                fontStyle: 'normal',
                fontSize: '16px',
                lineHeight: '20px',
                letterSpacing: '0px'
              }}
              className="text-gray-600"
            >
              {jobs.length}/10
            </span>
            <button
              onClick={() => setIsOpen(false)}
              className="p-1.5 hover:bg-gray-100 rounded-full transition-colors"
              aria-label="Close panel"
            >
              <X className="w-5 h-5 text-gray-700 font-semibold" strokeWidth={2.5} />
            </button>
          </div>

          {/* Jobs list */}
          <div className="overflow-y-auto px-4 py-3 space-y-3" style={{ maxHeight: 'calc(100vh - 140px)' }}>
            {jobs.length === 0 ? (
              <div className="text-center py-12 text-gray-500 text-sm font-medium">
                No generation jobs yet
              </div>
            ) : (
              jobs.map((job) => {
                const isRunning = job.status === 'RUNNING';
                const isQueued = job.status === 'QUEUED';
                const isClickable = job.status === 'SUCCEEDED' || job.status === 'RUNNING';
                const isFailed = job.status === 'FAILED' || job.status === 'CANCELED';

                // Format: "Job Name status" in one line
                const statusText = getStatusText(job.status);
                const displayText = `${job.displayName} ${statusText}`;

                return (
                  <div
                    key={job.id}
                    className={`group relative w-full text-left px-4 py-3.5 rounded-xl transition-all ${
                      getStatusColor(job.status)
                    } ${
                      isClickable
                        ? 'hover:shadow-sm cursor-pointer'
                        : 'cursor-default'
                    }`}
                  >
                    {/* "New!" badge - overlapping top-left for succeeded jobs */}
                    {job.isNew && isClickable && (
                      <span className="absolute -top-1.5 -left-1.5 text-xs font-semibold text-green-700 bg-white border border-green-200 px-2 py-0.5 rounded-full whitespace-nowrap z-20">
                        New!
                      </span>
                    )}

                    {/* Delete button - visible on hover for all items
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        // TODO: Handle delete job
                      }}
                      className="absolute -left-2 -top-2 w-5 h-5 bg-white border border-gray-300 rounded-full flex items-center justify-center hover:bg-gray-50 transition-all opacity-0 group-hover:opacity-100 z-10"
                      aria-label="Remove job"
                    >
                      <X className="w-3 h-3 text-gray-600" strokeWidth={2.5} />
                    </button> */}

                    <button
                      onClick={() => isClickable && handleJobClick(job)}
                      disabled={!isClickable}
                      className={`w-full text-left flex items-center justify-between gap-2 ${
                        isClickable ? 'cursor-pointer' : 'cursor-default'
                      }`}
                    >
                      <div className="flex-1 min-w-0 flex items-center gap-2">
                        <span className={`text-sm font-medium truncate ${getStatusTextColor(job.status)}`}>
                          {displayText}
                        </span>
                        {isRunning && (
                          <Loader2 className="w-3.5 h-3.5 animate-spin text-gray-600 flex-shrink-0" strokeWidth={2} />
                        )}
                      </div>
                      {isClickable && (
                        <div className="w-6 h-6 bg-white border border-gray-300 rounded-full flex items-center justify-center flex-shrink-0">
                          <ArrowRight className="w-3.5 h-3.5 text-green-800" strokeWidth={2.5} />
                        </div>
                      )}
                    </button>
                  </div>
                );
              })
            )}
          </div>
        </div>
      </div>

      {/* Overlay when open */}
      {isOpen && (
        <div
          className="fixed inset-0 bg-black/20 z-30"
          onClick={() => setIsOpen(false)}
        />
      )}
    </>
  );
}
