import { NextResponse } from "next/server";
import { getUser, hasEnoughTokens, createGenerationJob, updateGenerationJobStatus, refundTokens, getBrandByWebsiteUrl } from "@/lib/db/queries";
import { randomUUID } from "crypto";

const TOKENS_COST_PER_GENERATION = 50;

export async function POST(req: Request) {
  const webhookUrl = process.env.N8N_WEBHOOK_URL + 'main-free-workflow';
  const webhookKey = process.env.N8N_WEBHOOK_KEY;
  
  if (!webhookUrl) {
    return NextResponse.json({ error: "Webhook URL not configured" }, { status: 500 });
  }

  try {
    const { url } = await req.json();
    // Check if user is authenticated
    const user = await getUser();
    if (!user) {
      return NextResponse.json({ 
        error: "Unauthorized", 
        error_code: "AUTH_REQUIRED",
        website_url: url // Include website URL for redirect after login
      }, { status: 401 });
    }

    if (!url || typeof url !== "string") {
      return NextResponse.json({ error: "Missing url" }, { status: 400 });
    }

    // Check if user has enough tokens before proceeding
    const hasTokens = await hasEnoughTokens(user.id, TOKENS_COST_PER_GENERATION);
    if (!hasTokens) {
      return NextResponse.json({ 
        error: "Insufficient tokens", 
        error_code: "INSUFFICIENT_TOKENS",
        tokens_required: TOKENS_COST_PER_GENERATION
      }, { status: 402 }); // Payment Required
    }

    // Generate a unique job ID for this generation
    const jobId = randomUUID();

    // Try to find existing brand by website URL (optional - brandId can be null)
    const existingBrand = await getBrandByWebsiteUrl(user.id, url);

    let job;
    try {
      // Create generation job (this reserves tokens atomically)
      job = await createGenerationJob(user.id, {
        id: jobId,
        prompt: undefined, // Will be generated by n8n
        params: {}, // Default params
        tokensCost: TOKENS_COST_PER_GENERATION,
        brandId: existingBrand?.id,
        insightSource: 'auto',
        archetypeInputs: {},
      });
    } catch (error) {
      if (error instanceof Error && error.message.includes('Insufficient')) {
        return NextResponse.json({ 
          error: "Insufficient tokens", 
          error_code: "INSUFFICIENT_TOKENS",
          tokens_required: TOKENS_COST_PER_GENERATION
        }, { status: 402 }); // Payment Required
      }
      throw error;
    }
    // Send job_id to n8n webhook (as per ad_generation_flow.md)
    try {
      const res = await fetch(webhookUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-agent-key": webhookKey || "",
        },
        body: JSON.stringify({
          job_id: jobId,
          website_url: url, // Pass website URL so n8n can handle brand extraction if needed
        }),
      });

      if (!res.ok) {
        // Webhook call failed - mark job as failed and refund tokens
        const errorText = await res.text().catch(() => 'Webhook request failed');
        await updateGenerationJobStatus(
          jobId,
          'FAILED',
          'WEBHOOK_ERROR',
          errorText
        );
        await refundTokens(user.id, TOKENS_COST_PER_GENERATION, jobId);
        
        return NextResponse.json({ 
          error: "Failed to trigger generation", 
          job_id: jobId,
          tokens_refunded: TOKENS_COST_PER_GENERATION
        }, { status: res.status });
      }

      // Job created and webhook triggered successfully
      // n8n will handle the generation and update the job status
      return NextResponse.json({
        job_id: jobId,
        status: 'QUEUED',
        tokens_used: TOKENS_COST_PER_GENERATION,
        message: 'Generation job created and queued'
      }, { status: 202 }); // 202 Accepted - job is queued

    } catch (webhookError) {
      // Webhook call failed - mark job as failed and refund tokens
      console.error('Webhook error:', webhookError);
      await updateGenerationJobStatus(
        jobId,
        'FAILED',
        'WEBHOOK_ERROR',
        webhookError instanceof Error ? webhookError.message : 'Unknown webhook error'
      );
      await refundTokens(user.id, TOKENS_COST_PER_GENERATION, jobId);
      
      return NextResponse.json({ 
        error: "Failed to trigger generation", 
        job_id: jobId,
        tokens_refunded: TOKENS_COST_PER_GENERATION
      }, { status: 502 });
    }
  } catch (e) {
    console.error('Generation error:', e);
    return NextResponse.json({ 
      error: "Internal server error",
      message: e instanceof Error ? e.message : "Unknown error"
    }, { status: 500 });
  }
}
