import { randomUUID } from 'crypto';
import { createGenerationJob } from './generation';

/**
 * Creates a new quick ads generation job
 * - Generates 10 ads total (5 per format: 1:1 and 16:9)
 * - Tokens will be deducted when job is created via reserveTokens
 * - Sets autoGenerated flag to true
 */
export async function createQuickAdsJob(
  userId: string,
  brandId: string,
  tokensCost: number = 50
) {
  const jobId = randomUUID();
  
  const job = await createGenerationJob(userId, {
    id: jobId,
    prompt: undefined, // Will be generated by n8n
    params: {}, // Default params
    tokensCost: 0, // Will be set via reserveTokens in the route
    brandId,
    insightSource: 'auto',
    archetypeInputs: {},
    formats: ['1:1', '16:9'], // Always generate both formats for quick ads
    autoGenerated: true,
  });

  return job;
}
